# Generated by Django 6.1 on 2026-09-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Indian', 'Indian Food'), ('Chinese', 'Chinese Food'), ('Pasta', 'Pasta'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
