# Generated by Django 6.1 on 2026-09-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Indian', 'Indian Food'), ('Chinese', 'Chinese Food'), ('Pasta', 'Pasta'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks'), ('Jain', 'Jain Food')], max_length=50),
        ),
    ]
