# Generated by Django 6.1 on 2026-09-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Indian', 'Indian Food'), ('Chinese', 'Chinese Food'), ('Pasta', 'Pasta'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks'), ('Jain', 'Jain Food')], max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order Placed', max_length=30),
        ),
    ]
