# Generated by Django 6.1.1 on 2026-09-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_food_category_alter_food_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Indian', 'Indian Food'), ('Chinese', 'Chinese Food'), ('Pasta', 'Pasta'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks'), ('Jain', 'Jain Food')], max_length=255),
        ),
    ]
