# Generated by Django 6.1.1 on 2026-09-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='food_images/'),
        ),
    ]
